### ISSUE TITLE
Add Global Chatrooms Tables, Permissions 

### ISSUE THREAD

**Issue by likt0r** [faktenforum/faktenforum#67]
```[tasklist]
### Tasks
- [ ] All Users should be able to receive and send Messages
- [ ] Moderator should be able to moderate the user messages
- [ ] User Role restricted Channels
```
