### ISSUE TITLE
Create Account Deletion

### ISSUE THREAD

**Issue by likt0r** [faktenforum/faktenforum#71]
```[tasklist]
### Tasks
- [ ] Create Triggers ever Content which should be deleted, will be deleted
- [ ] Create Triggers anonymize Content which need to be
- [ ] Create triggers which delete content
- [ ] Legal clarification Account deletion
```
